### ISSUE TITLE
No response when pressing any Button except HOME.

### ISSUE THREAD

**Issue by fog-zs** [tik-choco/tc-website#1]
![image](https://user-images.githubusercontent.com/38463346/221390119-1380b7f0-d40c-44b2-8b1d-3ad9c521bc8f.png)
Home以外のButtonを押しても反応がないです

**Comment by fog-zs** [comment]
![image](https://user-images.githubusercontent.com/38463346/221390119-1380b7f0-d40c-44b2-8b1d-3ad9c521bc8f.png)
Home以外のButtonを押しても反応がないです

**Comment by ryuga93** [comment]
こちらのブランチで修正しました。
https://github.com/tik-choco/tc-website/tree/tab-fix
